MobileRobot:
  camera_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - PanJoint
      - TiltJoint
    gains:
      PanJoint:
        p: 0.1
        i: 0.0
        d: 0.05
      TiltJoint:
        p: 0.1
        i: 0.0
        d: 0.5
