teleop:
  move:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: /cmd_vel
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 1.0
      -
        axis: 0
        target: angular.z
        scale: 2.0
  pan_tilt:
    type: topic
    message_type: geometry_msgs/Vector3
    topic_name: /cmd_joint_vel
    axis_mappings:
      -
        axis: 4
        target: y
        scale: 2.0
      -
        axis: 3
        target: z
        scale: 2.0
